// Generated by scripts/generate-native-contract.mjs. Do not edit.

enum NativeContract {
    static let pluginName = "CapacitorOidc"

    enum Method {
        static let configure = "configure"
        static let open = "open"
        static let cancel = "cancel"
        static let storageSet = "storageSet"
        static let storageGet = "storageGet"
        static let storageRemove = "storageRemove"
        static let storageGetAllKeys = "storageGetAllKeys"
        static let setSessionSnapshot = "setSessionSnapshot"
    }
    enum Field {
        static let url = "url"
        static let callbackUrl = "callbackUrl"
        static let prefersEphemeralWebBrowserSession = "prefersEphemeralWebBrowserSession"
        static let keychainAccessGroup = "keychainAccessGroup"
        static let keychainAccessibility = "keychainAccessibility"
        static let namespace = "namespace"
        static let key = "key"
        static let value = "value"
        static let keys = "keys"
    }
    enum ErrorCode {
        static let authSessionInProgress = "AUTH_SESSION_IN_PROGRESS"
        static let userCancelled = "USER_CANCELLED"
        static let browserUnavailable = "BROWSER_UNAVAILABLE"
        static let invalidCallback = "INVALID_CALLBACK"
        static let secureStorageError = "SECURE_STORAGE_ERROR"
        static let unsupportedRuntime = "UNSUPPORTED_RUNTIME"
    }
    enum KeychainAccessibility {
        static let afterFirstUnlockThisDeviceOnly = "afterFirstUnlockThisDeviceOnly"
        static let whenUnlockedThisDeviceOnly = "whenUnlockedThisDeviceOnly"
    }
}
