// Generated by scripts/generate-native-contract.mjs. Do not edit.
package com.jojopirker.capacitor.oidc;

final class NativeContract {

    static final String PLUGIN_NAME = "CapacitorOidc";

    static final String METHOD_CONFIGURE = "configure";
    static final String METHOD_OPEN = "open";
    static final String METHOD_CANCEL = "cancel";
    static final String METHOD_STORAGE_SET = "storageSet";
    static final String METHOD_STORAGE_GET = "storageGet";
    static final String METHOD_STORAGE_REMOVE = "storageRemove";
    static final String METHOD_STORAGE_GET_ALL_KEYS = "storageGetAllKeys";
    static final String METHOD_SET_SESSION_SNAPSHOT = "setSessionSnapshot";
    static final String FIELD_URL = "url";
    static final String FIELD_CALLBACK_URL = "callbackUrl";
    static final String FIELD_PREFERS_EPHEMERAL_WEB_BROWSER_SESSION = "prefersEphemeralWebBrowserSession";
    static final String FIELD_KEYCHAIN_ACCESS_GROUP = "keychainAccessGroup";
    static final String FIELD_KEYCHAIN_ACCESSIBILITY = "keychainAccessibility";
    static final String FIELD_NAMESPACE = "namespace";
    static final String FIELD_KEY = "key";
    static final String FIELD_VALUE = "value";
    static final String FIELD_KEYS = "keys";
    static final String ERROR_AUTH_SESSION_IN_PROGRESS = "AUTH_SESSION_IN_PROGRESS";
    static final String ERROR_USER_CANCELLED = "USER_CANCELLED";
    static final String ERROR_BROWSER_UNAVAILABLE = "BROWSER_UNAVAILABLE";
    static final String ERROR_INVALID_CALLBACK = "INVALID_CALLBACK";
    static final String ERROR_SECURE_STORAGE_ERROR = "SECURE_STORAGE_ERROR";
    static final String ERROR_UNSUPPORTED_RUNTIME = "UNSUPPORTED_RUNTIME";
    static final String KEYCHAIN_ACCESSIBILITY_AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY = "afterFirstUnlockThisDeviceOnly";
    static final String KEYCHAIN_ACCESSIBILITY_WHEN_UNLOCKED_THIS_DEVICE_ONLY = "whenUnlockedThisDeviceOnly";

    private NativeContract() {}
}
